[project]
name = "triange-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nimrod Oren", email = "nimrodo@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain-google-genai>=4.4.0",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
triange-agent = "triange_agent:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
    "ty>=0.0.81",
]
